# Generated by Django 2.1.7 on 2019-05-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_administrator_landlord_startenant_student_verifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicile',
            name='photo',
            field=models.ImageField(default='none', upload_to='final/residence_pictures'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='verifieduser',
            table='final_verified_users    ',
        ),
    ]
