# Generated by Django 2.1.7 on 2019-05-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0001_initial'),
        ('pybb', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('final', '0004_auto_20190509_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='verifieduser_ptr',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='verifieduser_ptr',
        ),
        migrations.RemoveField(
            model_name='startenant',
            name='verifieduser_ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verifieduser_ptr',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Landlord',
        ),
        migrations.DeleteModel(
            name='StarTenant',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
