# Generated by Django 2.1.7 on 2019-05-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0001_initial'),
        ('postman', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('final', '0005_auto_20190510_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifieduser',
            name='registereduser_ptr',
        ),
        migrations.DeleteModel(
            name='VerifiedUser',
        ),
    ]
