# Generated by Django 2.1.7 on 2019-05-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_auto_20190510_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='permission_level',
            field=models.IntegerField(default=-1),
        ),
    ]
