# Generated by Django 2.1.7 on 2019-05-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0007_registereduser_permission_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomicilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.ImageField(upload_to='final/residence_pictures')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.Domicile')),
            ],
            options={
                'db_table': 'final_residence_photos',
            },
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='permission_level',
            field=models.IntegerField(default=4),
        ),
    ]
