# Generated by Django 2.1.7 on 2019-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0008_auto_20190512_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilephoto',
            name='photo_url',
            field=models.ImageField(null=True, upload_to='final/residence_pictures'),
        ),
    ]
