# Generated by Django 2.1.7 on 2019-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0010_auto_20190512_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicile',
            name='district',
            field=models.CharField(default='Park Merced', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domicile',
            name='tenants',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
